// Portability, enforced rather than asserted in prose.
//
// Two claims are made about this skill: it runs from a bare copy with nothing
// installed, and it depends on no host-specific API so the same files work under
// Codex. Both are easy to break by accident with one import, and neither failure
// shows up locally, where node_modules happens to exist. So they are tested.

import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');

// Directories that ship as part of the skill. `scripts/` is development-time
// tooling and may use ajv; `test/` is not shipped either.
const SHIPPED = ['bin', 'renderers', 'validate', 'scaffold', 'editor'];

function sourceFiles(directory) {
  const base = path.join(root, directory);
  if (!fs.existsSync(base)) return [];
  const out = [];
  const walk = (current) => {
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const full = path.join(current, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.name.endsWith('.mjs')) out.push(full);
    }
  };
  walk(base);
  return out;
}

const shippedSources = SHIPPED.flatMap(sourceFiles);

test('there is something to check', () => {
  assert.ok(shippedSources.length > 5, 'expected shipped source files');
});

test('no shipped file imports a package: the skill runs with no node_modules', () => {
  const offenders = [];
  for (const file of shippedSources) {
    const source = fs.readFileSync(file, 'utf8');
    const imports = [...source.matchAll(/^\s*(?:import|export)\s[^'"]*from\s*['"]([^'"]+)['"]/gm)]
      .map((match) => match[1]);
    const dynamic = [...source.matchAll(/\bimport\(\s*['"]([^'"]+)['"]/g)].map((match) => match[1]);
    for (const specifier of [...imports, ...dynamic]) {
      const isRelative = specifier.startsWith('./') || specifier.startsWith('../');
      const isNodeBuiltin = specifier.startsWith('node:');
      if (!isRelative && !isNodeBuiltin) {
        offenders.push(`${path.relative(root, file)} -> ${specifier}`);
      }
    }
  }
  assert.deepEqual(offenders, [], 'shipped code may import only relative paths and node: builtins');
});

test('the editor\'s shared modules run in a browser: no node: imports', () => {
  const offenders = sourceFiles('editor')
    .filter((file) => /^\s*(?:import|export)\s[^'"]*from\s*['"]node:/m.test(fs.readFileSync(file, 'utf8')))
    .map((file) => path.relative(root, file));
  assert.deepEqual(offenders, []);
});

test('the generated validator carries no runtime dependency', () => {
  const generated = path.join(root, 'renderers', 'shared', 'generated-validators.mjs');
  const source = fs.readFileSync(generated, 'utf8');
  assert.ok(!source.includes('require('), 'ajv\'s standalone output must have its helpers inlined');
  assert.match(source, /Generated by scripts\/generate-validators\.mjs/);
});

test('no shipped file reaches for a host-specific API', () => {
  // The skill is driven through a plain CLI. Anything that assumes a particular
  // agent host would silently not work in the other one.
  const forbidden = [/\bAskUserQuestion\b/, /\bwindow\./, /\bdocument\./];
  const offenders = [];
  for (const file of shippedSources) {
    const source = fs.readFileSync(file, 'utf8');
    // Comments may legitimately discuss the browser viewer or the asking model.
    const code = source.replace(/\/\/[^\n]*/g, '').replace(/\/\*[\s\S]*?\*\//g, '');
    for (const pattern of forbidden) {
      if (pattern.test(code)) offenders.push(`${path.relative(root, file)} matches ${pattern}`);
    }
  }
  assert.deepEqual(offenders, []);
});
